name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out ActionForge ðŸš€
on: [push]

jobs:
  this-is-a-workflow:
    runs-on: ubuntu-latest
    name: Run Graph
    steps:
      - name: Run Graph
        uses: actionforge/action@866e7df1ce5e84a2b32fda7414812ae72000dae8 # v0.14.6
        with:
          graph-file: go.act

          inputs: ${{ toJson(inputs) }}
          secrets: ${{ toJson(secrets) }}
          matrix: ${{ toJson(matrix) }}
          needs: ${{ toJson(needs) }}
        
